### ISSUE TITLE
Unnecessary restrictions on NQF0032

### ISSUE THREAD

**Issue by kclaes** [pophealth/popHealth#23]
We’re checking off all our metrics, but we came across a strange requirement in metric NFQ0032, which was explicitly put in as part of a bug fix by Andre on 2/12: “fixed “bug” in measure where encounters should ==1”.

However, looking at the official (?) metrics definition given on [qualiftyforum.org](http://www.qualityforum.org/MeasureDetails.aspx?actid=0&SubmissionId=393#p=3&s=n&so=a) , it says:
- Numerator: **One or more** Pap tests during the measurement year or the two years prior to the measurement year.
- Denominator: Women 21–64 years of age during the measurement year.

Can this restriction be lifted again? Or why was it put in?

**Comment by ssayer** [comment]
The description does not convey what the actual measure login is. This is an error in the measure definition, however we are following "the letter of the law" in this case. The actual logic of that measure says that it must be == 1. This has been fixed in Stage 2, however we won't be changing the measure definition until we add Stage 2 support.

**Comment by kclaes** [comment]
Could you provide a link to "the letter of the law"?
We have a script from a certification agency that we need to adhere to and this metric fails because of the strict requirement of only being allowed to have had exactly one encounter.
