### ISSUE TITLE
Enable CCR Import

### ISSUE THREAD

**Issue by mabuzer** [pophealth/popHealth#28]
I have a small question related to CCR import, I've been looking around how to enable JAVA, but nothing worked, I tried to look into the configuration files, I found this file: pophealth.conf at the home directory. it implies that you are using rvm to control which version of ruby to use, I changed that to 'rvm use jruby', and restarted the vmware (the one I downloaded from your web-site), but also I still get linux-i686 as ruby platform...Could you please help me how to force pophealth to use jruby?

My objective is to enable CCR support as it seems to be disabled by default.

**Comment by ssayer** [comment]
Are you interested in running JRuby in general or just to run the CCR Importer? Since version 1.4 we don't require JRuby for CCR import anymore, our CCR importer was rewritten to use MRI. I'm not sure when you downloaded the image, so I dont' know what version you're running.

If you just want to use JRuby, it may be that the image is defaulting to using the MRI interpreter instead of JRuby. The rvm command only lasts as long as you are logged into the shell. If you want to switch to JRuby as the default, try following these instructions:

https://rvm.io/rubies/default/

**Comment by mabuzer** [comment]
So which module I can use to import CCR files into pophealth, wiki says, to use CCR you have to use JRuby...
